### ISSUE TITLE
Nova versão do logotipo

### ISSUE THREAD

**Issue by zeyuri** [Ada-Code-Studio/AdaCodeStudio#11]
Vim trabalhando numa nova versão da logo durante o final de semana.

As principais mudanças são: 

- Ajustes visuais de equilibrio de espaçamentos no Logo

> Os principais ajustes foram no peso de alguns traços e no equilibrio visual de alguns elementos que estavam desalinhados

- escolha da tipografia que acompanha o Logo
> Foi escolhida a tipografia [Jura](https://fonts.google.com/specimen/Jura) que é uma fonte de licensa livre no estilo sans-serif que segue a Linhagem de fontes Eurostile.  Possui curvas harmônicas que contrastam e combinam com o aspecto mais reto e direto do ícone. Outro aspecto interessante é que a fonte possui o formato de fonte variável que pode ser manipulado via css de forma livre.

![Logo](https://user-images.githubusercontent.com/4077827/88560498-9666fd80-d004-11ea-8828-b0e669b7a317.png)

[Versão em vetor
](https://drive.google.com/file/d/1UuoVTxhvTOzO7KAV9DQF_gVNIcBiHzL6/view?usp=sharing)

Próximos passos:

- Fazer o favicon
- Versão negativa (dark mode)
- Design system

**Comment by FabriDamazio** [comment]
Lindo @zeyuri !
Adorei a fonte também.

Como você sugere controlarmos os próximos passos? Acho que podemos lançar uma issue para cada, o que acha?

**Comment by zeyuri** [comment]
Dá pra criar uma issue pra todo o design system, vou criar um arquivo público no figma que da pra irmos acompanhando e comentando lá.

**Comment by FabriDamazio** [comment]
> Dá pra criar uma issue pra todo o design system, vou criar um arquivo público no figma que da pra irmos acompanhando e comentando lá.

Perfeito, pode me mandar uma versão pra gente atualizar já a imagem da organização aqui no gh?

**Comment by zeyuri** [comment]
@FabriDamazio precisa ser em svg ou em png?

**Comment by FabriDamazio** [comment]
> @FabriDamazio precisa ser em svg ou em png?

PNG.

**Comment by zeyuri** [comment]
Segue a logo e o logotipo

![logo](https://user-images.githubusercontent.com/4077827/88576075-3a5ba380-d01b-11ea-85be-23eae9dd3074.png)
![logotipo](https://user-images.githubusercontent.com/4077827/88576076-3af43a00-d01b-11ea-8fab-05b889a7de65.png)

**Comment by FabriDamazio** [comment]
Logotipo da organização atualizado. Obrigado @zeyuri

**Comment by FabriDamazio** [comment]
@zeyuri  estou fechando aqui e criei a issue para o design system #16
